<a href="https://colab.research.google.com/github/OydinZoidova/colab_uchun2/blob/main/pandas_2_vazifa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pandas import Series

In [3]:
from google.colab import files
yuklangan=files.upload()

Saving pandas_homework_dirty_data_2150_rows.csv to pandas_homework_dirty_data_2150_rows.csv

In [4]:
df=pd.read_csv('pandas_homework_dirty_data_2150_rows.csv')
df.head()

   order_id    shop  product     city amount   shop_date
0         1  Shop B   Laptop  Bukhara   3950  16.01.2025
1         2  Shop E   Laptop      NaN   1393         NaN
2         3     NaN  Monitor      NaN  1,200  17.09.2025
3         4     NaN      NaN  Bukhara   2456  21.01.2025
4         5     NaN   Laptop      NaN   4715  14.01.2025

In [5]:
df.isnull().sum()

order_id       0
shop         610
product      601
city         618
amount       335
shop_date    224
dtype: int64

In [6]:
df.shape

(2150, 6)

In [7]:
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_")
df.head(15)

    order_id    shop  product       city    amount   shop_date
0          1  Shop B   Laptop    Bukhara      3950  16.01.2025
1          2  Shop E   Laptop        NaN      1393         NaN
2          3     NaN  Monitor        NaN     1,200  17.09.2025
3          4     NaN      NaN    Bukhara      2456  21.01.2025
4          5     NaN   Laptop        NaN      4715  14.01.2025
5          6  Shop A      NaN    Andijan      1936  01.01.2025
6          7  Shop C      NaN    Bukhara      1755  29.09.2025
7          8  Shop A      NaN  Samarkand  1000 som  31.02.2025
8          9  Shop D   Laptop   Tashkent      2593  09.02.2025
9         10     NaN      NaN    Andijan       NaN  12.11.2025
10        11  Shop D   Laptop  Samarkand      1472  07.08.2025
11        12  Shop D      NaN   Namangan       669  08.08.2025
12        13     NaN   Laptop        NaN      1159  07.12.2025
13        14  Shop D    Phone   Tashkent       365  19.10.2025
14        15     NaN    Mouse   Namangan      1158  28.09.2025

In [8]:
df.amount

0        3950
1        1393
2       1,200
3        2456
4        4715
        ...
2145    1,200
2146      NaN
2147       11
2148     3062
2149     3427
Name: amount, Length: 2150, dtype: object

In [9]:
df['amount_original'] = df['amount'].astype(str)

In [10]:
df=df.dropna(subset=['shop'])
df.shape

(1540, 7)

In [11]:
df['amount_original'] = df['amount'].astype(str)

In [12]:
s = (df['amount_original']
     .str.replace(r'[^0-9\.,-]', '', regex=True)
     .str.replace(',', '.', regex=False)
)
df['amount_clean'] = pd.to_numeric(s, errors='coerce')
bad = df[df['amount_clean'].isna() & df['amount_original'].notnull()]
print(bad['amount_original'].unique()[:50])
df['amount'] = df['amount_clean'].astype('Float64')

['nan']

In [13]:
df.info

<bound method DataFrame.info of       order_id    shop  product       city  amount   shop_date  \
0            1  Shop B   Laptop    Bukhara  3950.0  16.01.2025
1            2  Shop E   Laptop        NaN  1393.0         NaN
5            6  Shop A      NaN    Andijan  1936.0  01.01.2025
6            7  Shop C      NaN    Bukhara  1755.0  29.09.2025
7            8  Shop A      NaN  Samarkand  1000.0  31.02.2025
...        ...     ...      ...        ...     ...         ...
2142      1611  Shop B  Monitor    Andijan  2890.0         NaN
2144       513  Shop D    Phone        NaN  2832.0  27.07.2025
2147      1947  Shop E      NaN  Samarkand    11.0  30.10.2025
2148      1074  Shop D      NaN   Namangan  3062.0  30.11.2025
2149      1692  Shop B      NaN    Andijan  3427.0  00.00.2026

     amount_original  amount_clean
0               3950        3950.0
1               1393        1393.0
5               1936        1936.0
6               1755        1755.0
7           1000 som        1000.0
...              ...           ...
2142            2890        2890.0
2144            2832        2832.0
2147              11          11.0
2148            3062        3062.0
2149            3427        3427.0

[1540 rows x 8 columns]>

In [14]:
df.isna().sum()

order_id             0
shop                 0
product            436
city               425
amount             244
shop_date          152
amount_original      0
amount_clean       244
dtype: int64

In [15]:
df["shop_date"] = pd.to_datetime(df["shop_date"], errors="coerce")

/tmp/ipykernel_11394/3839746688.py:1: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["shop_date"] = pd.to_datetime(df["shop_date"], errors="coerce")

In [16]:
df["shop_date"] = df["shop_date"].fillna(df["shop_date"]).mean()

df['shop_date'] = pd.to_datetime(df['shop_date'], errors='coerce', dayfirst=True)
df['shop_date'] = df['shop_date'].fillna(df['shop_date'].mean())

In [17]:
df.isnull().sum()

order_id             0
shop                 0
product            436
city               425
amount             244
shop_date            0
amount_original      0
amount_clean       244
dtype: int64

In [18]:
df['amount']=pd.to_numeric(df['amount'], errors='coerce')
df.head()

,order_id,shop,product,city,amount,shop_date,amount_original,amount_clean
0,1,Shop B,Laptop,Bukhara,3950.0,2025-06-26 22:27:39.740259840,3950,3950.0
1,2,Shop E,Laptop,NaN,1393.0,2025-06-26 22:27:39.740259840,1393,1393.0
5,6,Shop A,NaN,Andijan,1936.0,2025-06-26 22:27:39.740259840,1936,1936.0
6,7,Shop C,NaN,Bukhara,1755.0,2025-06-26 22:27:39.740259840,1755,1755.0
7,8,Shop A,NaN,Samarkand,1000.0,2025-06-26 22:27:39.740259840,1000 som,1000.0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1540 entries, 0 to 2149
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         1540 non-null   int64
 1   shop             1540 non-null   object
 2   product          1104 non-null   object
 3   city             1115 non-null   object
 4   amount           1296 non-null   Float64
 5   shop_date        1540 non-null   datetime64[ns]
 6   amount_original  1540 non-null   object
 7   amount_clean     1296 non-null   float64
dtypes: Float64(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 109.8+ KB

In [20]:
df.isnull().sum()

order_id             0
shop                 0
product            436
city               425
amount             244
shop_date            0
amount_original      0
amount_clean       244
dtype: int64

In [21]:
#df['amount']=df['amount'].fillna(df['amount'].mean())

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1540 entries, 0 to 2149
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         1540 non-null   int64
 1   shop             1540 non-null   object
 2   product          1104 non-null   object
 3   city             1115 non-null   object
 4   amount           1296 non-null   Float64
 5   shop_date        1540 non-null   datetime64[ns]
 6   amount_original  1540 non-null   object
 7   amount_clean     1296 non-null   float64
dtypes: Float64(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 109.8+ KB

In [23]:
df.head()

,order_id,shop,product,city,amount,shop_date,amount_original,amount_clean
0,1,Shop B,Laptop,Bukhara,3950.0,2025-06-26 22:27:39.740259840,3950,3950.0
1,2,Shop E,Laptop,NaN,1393.0,2025-06-26 22:27:39.740259840,1393,1393.0
5,6,Shop A,NaN,Andijan,1936.0,2025-06-26 22:27:39.740259840,1936,1936.0
6,7,Shop C,NaN,Bukhara,1755.0,2025-06-26 22:27:39.740259840,1755,1755.0
7,8,Shop A,NaN,Samarkand,1000.0,2025-06-26 22:27:39.740259840,1000 som,1000.0

In [24]:
df.isnull().sum()

order_id             0
shop                 0
product            436
city               425
amount             244
shop_date            0
amount_original      0
amount_clean       244
dtype: int64

In [25]:
df['product']=df['product'].fillna(df['product'].mode()[0])

In [26]:
df.isnull().sum()

order_id             0
shop                 0
product              0
city               425
amount             244
shop_date            0
amount_original      0
amount_clean       244
dtype: int64

In [32]:
df['city']=df['city'].ffill()
df.shape

/tmp/ipykernel_11394/1463477524.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city']=df['city'].ffill()

(1115, 8)

In [33]:
df.isnull().sum()

order_id             0
shop                 0
product              0
city                 0
amount             183
shop_date            0
amount_original      0
amount_clean       183
dtype: int64

In [34]:
df['amount']=df['amount'].ffill()

/tmp/ipykernel_11394/1936505130.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['amount']=df['amount'].ffill()

07.04-davomi pandas 3

In [35]:
df['amount']=(df['amount'].astype(str).str.replace(r"[^\d.]","",regex=True))

/tmp/ipykernel_11394/557155479.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['amount']=(df['amount'].astype(str).str.replace(r"[^\d.]","",regex=True))

In [36]:
df['amount']=pd.to_numeric(df['amount'], errors="coerce")

/tmp/ipykernel_11394/914900905.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['amount']=pd.to_numeric(df['amount'], errors="coerce")

In [37]:
df.isnull().sum()

order_id             0
shop                 0
product              0
city                 0
amount               0
shop_date            0
amount_original      0
amount_clean       183
dtype: int64